# Generated by Django 3.2.14 on 2023-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('timezone', models.CharField(choices=[('CST', 'CST'), ('EST', 'EST'), ('PST', 'PST'), ('MST', 'MST')], max_length=3)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('attended', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
    ]
